package com.example.marketstore.model


import android.os.Parcelable
import com.example.marketstore.R
import kotlinx.parcelize.Parcelize

@Parcelize
data class Product( var image: Int, var title: String, var price: Int, var kategory: CharCategory, var rating: Float , var description: String) : Parcelable {

    companion object {
        val INTENT_PARCELABLE = "OBJECT_INTENT"
    }
}

enum class CharCategory {
    SMARTPHONE,
    LAPTOP,
    COMPUTER
}


fun DataProduct():MutableList<Product>{
    val productList = mutableListOf<Product>()

    productList.add(Product(R.drawable.asustuf, "ASUS TUF F15 FX507ZC4", 775, CharCategory.LAPTOP, 4.5f, "ASUS TUF Gaming F15 FX507ZC4-I535B6M-O MECHA GRAY Mechanized endurance. Battlefield brilliance. Graphics: NVIDIA® GeForce RTX 3050 Laptop GPU 4GB GDDR6, 1790MHz* at 95W (1740MHz Boost Clock+50MHz OC, 80W+15W Dynamic Boost) • Processor: 12th Gen Intel® Core™ i5-12500H Processor 2.5 GHz (18M Cache, up to 4.5 GHz, 12 cores: 4 P-cores and 8 E-cores) • Display: 15.6-inch, FHD (1920 x 1080) 16:9, Value IPS-level, Anti-glare display, sRGB: 62.50%, Adobe: 47.34%, Refresh Rate: 144Hz, Adaptive-Sync, MUX Switch + Optimus • Memory: 8GB DDR4-3200 SO-DIMM • Storage: 512GB M.2 NVMe™ PCIe® 3.0 SSD"))
    productList.add(Product(R.drawable.acernitro, "ACER NITRO V15 ANV15-51-5115", 922, CharCategory.LAPTOP, 5.0f, "Nitro V 15 (ANV15-51-5115) • Processor: Intel® Core™ i5-13420H processor (12MB cache, up to 4.60Ghz) • OS: Windows 11 Home • Memory: 1*8GB DDR5 • Storage: 512GB SSD NVMe • Display: 15.6\" FHD LED IPS 144Hz • Graphics: NVIDIA® GeForce® RTX 4050 with 6GB of GDDR6"))
    productList.add(Product(R.drawable.loq, "LENOVO LOQ 15 12450HX", 799, CharCategory.LAPTOP, 4.7f, "Processor: Intel® Core™ i5-12450HX, 8C (4P + 4E) / 12T, P-core up to 4.4GHz, E-core up to 3.1GHz, 12MB • Graphics: Dedicated NVIDIA® GeForce RTX™ 3050 6GB GDDR6, Boost Clock 1732MHz, TGP 95W • Memory: 12GB/20GB DDR5-4800 SO-DIMM • Storage: 512GB SSD M.2 2242 PCIe® 4.0x4 NVMe® • Display: 15.6\" FHD (1920x1080) IPS 300nits Anti-glare, 100% sRGB, 144Hz, G-SYNC® • OS: Windows® 11 Home • Include: Microsoft Office Home & Student"))
    productList.add(Product(R.drawable.asusvivobook, "ASUS VIVOBOOK 14 A1404ZA", 387, CharCategory.LAPTOP, 4.7f, "Processor: Intel® Core™ i3-1215U • Graphics: Integrated Intel® UHD Graphics • Memory: 1x 8GB DDR4 onboard + 1x slot sodim (upgradeable) • Storage: 512GB M.2 NVMe PCIe 3.0 SSD • Display: 14.0-inch, FHD (1920 x 1080) 60Hz refresh rate, IPS-level Panel, Brightness: 250nits, 100% sRGB color gamut, Anti-glare display, 82% Screen-to-body ratio • OS: Windows® 11 Home • Include: Microsoft Office Home & Student"))
    productList.add(Product(R.drawable.pcallinone, "KOMPUTER ALL IN ONE Core i3-2100", 198, CharCategory.COMPUTER, 4.2f, "Spesifikasi Lengkap Core i3-2100: Resolusi: 1920x1080P 16:9 • Kompatibel dengan Motherboard: Chipset Intel H61M • CPU: Dual-core Quad-thread • RAM: 4GB/8GB (Pilihan) • Hard Drive: SSD 128G/256G (Pilihan) • Kartu Grafis: Kartu Grafis Inti Kinerja Tinggi • Parameter Layar: 19/22 inch IPS (Pilihan)"))
    productList.add(Product(R.drawable.pclenovo, "LENOVO PC IdeaCentre AIO 3 22ADA6", 356, CharCategory.COMPUTER, 4.7f, "PERFORMANCE Processor: AMD 3020e (2C / 2T, 1.2 / 2.6GHz, 1MB L2 / 4MB L3) • Graphics: Integrated AMD Radeon™ Graphics • Chipset: AMD SoC Platform • Monitor Support: Supports up to 2 independent displays via native display and 1 external monitor; supports external monitor via HDMI • Memory: 1x 8GB SO-DIMM DDR4-2400 • Memory Slots: 2x DDR4 SO-DIMM slots, dual-channel capable • Max Memory: Up to 16GB DDR4-2400 • Storage: 1TB HDD 5400rpm 2.5\" • Optane Memory: None • Storage Support: Up to 2x drives, 1x 2.5\" HDD + 1x M.2 SSD • 2.5\" HDD up to 1TB • M.2 SSD up to 512GB"))
    productList.add(Product(R.drawable.pcasus, "ASUS AIO M3200WUAK", 387, CharCategory.COMPUTER, 4.5f, "SPESIFIKASI Processor: AMD Ryzen™ 3 5300U Mobile Processor (4-core/8-thread, 6MB cache, up to 3.8 GHz max boost) • Graphics: Integrated AMD Radeon Graphics • Memory: 4GB/8GB DDR4 SO-DIMM • Storage: 1TB SATA 5400RPM 2.5″ HDD • Display: 21.5-inch, FHD (1920 x 1080) 16:9, Wide View, Anti-glare display, 250nits, sRGB:100% • OS: Windows® 11 Home • Include: Microsoft Office Trial/Microsoft Office Home & Student"))
    productList.add(Product(R.drawable.pcdell, "DELL INSPIRION AIO 5420", 121, CharCategory.COMPUTER, 4.5f, "Intel® Core™ i7-1355U Processor • RAM 16GB 3200 MHZ • SSD 512GB • Win11 Home • AIO • 3Yr Pro Support • Intel Iris XE • Non Touch Screen • 23.8\" +OHS 2021"))
    productList.add(Product(R.drawable.pcadvan, "ADVAN KOMPUTER ALL IN ONE PC AIO", 369, CharCategory.COMPUTER, 4.5f, "Garansi Resmi Advan Indonesia 1 Tahun Spesifikasi Advan OnePC AMD RYZEN5 5500U: • CPU: AMD RYZEN5 5500U 6 Core 12 Thread • GPU: Integrated Radeon Graphic • Display: 24” FHD 1920*1080 60 Hz 99%SRGB • RAM: 8GB 2 Slot SO-DIMM DDR4 3200Mhz • Storage: M.2 PCIe SSD 512GB • Camera: 5.0 MP • WIFI: 802.11 a/b/g/n/ac/ax • Bluetooth: V5.2 • Speaker: 2x box speakers 4Ω/3W • MIC: 2 pcs • Adapter: 19V / 4.74A，90W • Packaging Size: 604*150*471 mm • Free OS: Windows 11 Original • Bobot unit only: 5 Kg • Wireless Keyboard and mouse"))
    productList.add(Product(R.drawable.pchp, "PC HP All-in-one 27", 879, CharCategory.COMPUTER, 4.5f, "Sistem Operasi: Windows 11 Home Prosesor: Intel® Core™ Ultra 7 155U (hingga 4,8 GHz dengan Intel® Turbo Boost Technology, 12 MB L3 cache, 12 core, 14 thread) Grafis: Terintegrasi: Intel® Iris® Xᶱ Graphics Layar: 27 inci diagonal, FHD (1920 x 1080), IPS, tiga sisi micro-edge, anti-glare, 300 nits, 99% sRGB RAM: 16 GB DDR5-5600 MHz (2 x 8 GB) Slot Memori: 2 SODIMM Storage: 512 GB PCIe® NVMe™ M.2 SSD Interface Jaringan: Terintegrasi 10/100/1000 GbE LAN Teknologi Nirkabel: Realtek RTL8852BE Wi-Fi 6 (2x2) dan kartu nirkabel Bluetooth® 5.3 (mendukung kecepatan data gigabit) Adaptor Daya: 90 W Smart AC"))
    productList.add(Product(R.drawable.pchpenvy, "PC HP Envy Move All-in-One", 899, CharCategory.COMPUTER, 4.5f, "Prosesor: Intel Core i3-1315U (hingga 4,5 GHz, 10 MB L3 cache, 6 core, 8 thread) RAM: 8 GB (Onboard) Storage: 256 GB PCIe NVMe M.2 SSD Layar: 23,8 inci QHD (2560 x 1440), layar sentuh, IPS, tiga sisi micro-edge, BrightView, Low Blue Light, 300 nits Audio: Audio by B&O; Dual speaker 5 W Keyboard dan Mouse: HP 720 White Touchpad Integrated Bluetooth Keyboard Port I/O: Sisi: 1 USB Type-A 10Gbps (rate sinyal); 1 USB Type-C 10Gbps (rate sinyal, DisplayPort 1.4a) Video: 1 HDMI-in 1.4b Teknologi Nirkabel: Realtek RTL8852BE Wi-Fi 6 (2x2) dan Bluetooth 5.3 Form Factor: All-in-One Adaptor Daya: 90 W AC"))
    productList.add(Product(R.drawable.pcappleimac, "PC AIO Apple iMac 24-Inch M3", 299, CharCategory.COMPUTER, 4.5f, "Prosesor: Apple M3 chip dengan 8-core CPU (4 core performa dan 4 core efisiensi) GPU: 10-core GPU Ray Tracing: Dukungan ray tracing yang dipercepat perangkat keras Neural Engine: 16-core Neural Engine Bandwidth Memori: 100GB/s Media Engine: Dekode Video: Dukungan dekode perangkat keras untuk format H.264, HEVC, ProRes, dan ProRes RAW Encode Video: Mesin enkode video Dekode AV1: Dukungan dekode perangkat keras untuk format AV1 Storage: SSD 256GB (Konfigurasi dapat ditingkatkan hingga 1TB atau 2TB) RAM: 8GB RAM terpadu (Konfigurasi dapat ditingkatkan hingga 16GB atau 24GB RAM terpadu)"))
    productList.add(Product(R.drawable.pcacer, "PC AIO Acer C24-1650-UA93", 849, CharCategory.COMPUTER, 4.5f, "Processor: Intel Core i5-1135G7 RAM: 12GB DDR4 Storage: 512GB SSD Graphics: Integrated Intel Iris Xe Graphics Display: 23.8\" FHD (1920x1080) Operating System: Windows 10 Home"))
    productList.add(Product(R.drawable.ip13, "APPLE IPHONE 13 128GB", 615, CharCategory.SMARTPHONE, 4.5f, "Poin-poin fitur utama • Layar Super Retina XDR 6,1 inci • Mode Sinematik menambahkan kedalaman bidang yang dangkal dan pindah fokus secara otomatis di video Anda • Sistem kamera ganda canggih dengan kamera Wide dan Ultra Wide 12 MP; Gaya Fotografi, Smart HDR 4, mode Malam, perekaman HDR 4K Dolby Vision • Kamera depan TrueDepth 12 MP dengan mode Malam, perekaman HDR 4K Dolby Vision • Chip A15 Bionic untuk performa secepat kilat • Pemutaran video hingga 19 jam • Desain kokoh dengan Ceramic Shield • Level ketahanan air IP68 terdepan di industri • iOS 15 dilengkapi berbagai fitur baru untuk melakukan lebih banyak hal dengan iPhone • Mendukung aksesori MagSafe untuk kemudahan pemasangan dan pengisian daya nirkabel yang lebih cepat"))
    productList.add(Product(R.drawable.ip15, "APPLE IPHONE 15 128GB", 922, CharCategory.SMARTPHONE, 4.5f, "DYNAMIC ISLAND HADIR DI IPHONE 15 — Dynamic Island menampilkan gelembung pemberitahuan dan Aktivitas Langsung — jadi Anda tidak melewatkannya saat melakukan hal lain. Anda dapat melihat siapa yang menelepon, memeriksa status penerbangan Anda, dan banyak lagi. DESAIN INOVATIF — iPhone 15 dilengkapi dengan desain aluminium dan kaca berwarna yang tangguh. Tahan cipratan, air, dan debu.(1) Bagian depan Ceramic Shield lebih tangguh dibandingkan kaca ponsel pintar mana pun. Dan layar Super Retina XDR 6,1″(2) hingga 2x lebih terang di bawah sinar matahari dibandingkan iPhone 14. KAMERA UTAMA 48 MP DENGAN TELEFOTO 2X — Kamera Utama 48 MP mengambil gambar dengan resolusi super tinggi"))
    productList.add(Product(R.drawable.realme12, "REALME 12 PRO PLUS", 368, CharCategory.SMARTPHONE, 4.5f, "Ukuran Layar: 6,7\" inci Resolusi: 2412*1080（FHD+） Rasio Layar: 93% Refresh Rate: hingga 120Hz Touch Sampling Rate: Up to 240Hz Rasio Kontras: 5.000.000：1 Penyesuaian Kecerahan: 20.000 Level Kedalaman Warna: 1,07 Miliar Warna Warna Gamut: 100% DCI-P3 Teknologi: COP Ultra"))
    productList.add(Product(R.drawable.opporeno11, "OPPO RENO 11 5G", 344, CharCategory.SMARTPHONE, 4.5f, "OPPO Reno11 5G 8GB/256GB UKURAN DAN BOBOT Tinggi: sekitar 162.4mm Lebar: sekitar 74.3mm Ketebalan: Abu-abu Batu: sekitar 7.99mm, HijauOmbak: sekitar 8.04mm Berat: sekitar 182g PENYIMPANAN Kapasitas RAM dan ROM: 8GB+256GB Tipe RAM: LPDDR4x @ 2133MHz Spesifikasi ROM: UFS2.2 USB OTG: Didukung"))
    productList.add(Product(R.drawable.opporeno10, "OPPO RENO 10 PRO 5G", 322, CharCategory.SMARTPHONE, 4.5f, "UKURAN DAN BERAT Tinggi 162,3mm Lebar 74,2mm Ketebalan 7,89mm Berat 185g PENYIMPANAN Kapasitas RAM dan ROM 12GB + 256GB Tipe RAM: LPDDR4x @ 2133MHz 2×16bit Spesifikasi ROM: UFS2.2 @ 2Lanes HS-Gear3 USB OTG: Didukung KAMERA Belakang Kamera utama: 50MP; f/1.8; FOV 84.4°; lensa 6P; mendukung AF; mendukung OIS. Telefoto: 32MP; f/2.0; FOV 49,1°; lensa 6P; mendukung AF. Ultra Wide Angle: 8MP; f/2.2; FOV 112°; Lensa 5P, fokus tetap. Mendukung 2× optical zoom dan 20× digital zoom"))
    productList.add(Product(R.drawable.aceraspire, "ACER ASPIRE 3 SPIN", 755, CharCategory.LAPTOP, 4.5f, "Processor: Intel Core i3-N305 processor Octa-core (8 Cores, 8 Threads Up To 3.8 GHz) • Graphic: Integrated Intel® UHD Graphics • Memory: 8GB LPDDR5 • Storage: 512GB SSD PCIe Gen4 NVMe • Display: 14.0 IPS, WUXGA 1920 x 1200, Acer ComfyView LED-backlit TFT LCD supporting multi-touch, 16:10 aspect ratio • OS: Windows 11 Home • Include: Microsoft Office Home & Student"))
    productList.add(Product(R.drawable.msithin, "MSI THIN GF63", 979, CharCategory.LAPTOP, 4.5f, "Graphics: NVIDIA® GeForce RTX™ 2050 Laptop GPU Up to 1170MHz Boost Clock 45W Maximum Graphics Power with Dynamic Boost. *May vary by scenario • Processor: 12th Gen Intel® Core™ i5-12450H processor 8 cores (4 P-cores + 4 E-cores), Max Turbo Frequency 4.4 GHz • Memory: 8GB*1, DDR4-3200, 2 Slots, Max 64GB • Storage: 512GB*1 NVMe SSD PCIe Gen4, 1x M.2 SSD slot (NVMe PCIe Gen4), 1x 2.5 SATA HDD • Display: 15.6 FHD(1920x1080), 144Hz Refresh Rate, IPS-Level • Operating System: Windows 11 Home"))
    productList.add(Product(R.drawable.xiomi14, "XIAOMI 14", 738, CharCategory.SMARTPHONE, 4.5f, "Chipset: Qualcomm Snapdragon 8 Gen 3 • Layar: 6.36 inci, AMOLED, 120Hz, HDR10+ • Resolusi Layar: 2400 x 1080 piksel • Kamera Belakang: 50 MP (wide) + 50 MP (ultrawide) + 50 MP (telephoto) • Kamera Depan: 32 MP • RAM: 8GB atau 12GB • Penyimpanan Internal: 256GB atau 512GB • Baterai: 4500 mAh • Pengisian Daya: 67W fast charging, 50W wireless charging, 10W reverse wireless charging • Sistem Operasi: MIUI 15 berbasis Android 14 • Konektivitas: 5G, Wi-Fi 6E, Bluetooth 5.3, NFC"))
    productList.add(Product(R.drawable.pocox6, "POCO X6 5G", 246, CharCategory.SMARTPHONE, 4.5f, "Chipset: Qualcomm Snapdragon 7 Gen 1 • Layar: 6.67 inci, AMOLED, 120Hz, HDR10+ • Resolusi Layar: 2400 x 1080 piksel • Kamera Belakang: 64 MP (wide) + 8 MP (ultrawide) + 2 MP (macro) • Kamera Depan: 20 MP • RAM: 6GB atau 8GB • Penyimpanan Internal: 128GB atau 256GB • Baterai: 5000 mAh • Pengisian Daya: 67W fast charging • Sistem Operasi: MIUI berbasis Android 13 • Konektivitas: 5G, Wi-Fi 6, Bluetooth 5.2, NFC"))
    productList.add(Product(R.drawable.iqoo12, "IQ00 12", 699, CharCategory.SMARTPHONE, 4.5f, "Chipset: Qualcomm Snapdragon 8 Gen 3 • Layar: 6.78 inci, AMOLED, 144Hz, HDR10+ • Resolusi Layar: 3200 x 1440 piksel • Kamera Belakang: 50 MP (wide) + 13 MP (ultrawide) + 12 MP (telephoto) • Kamera Depan: 16 MP • RAM: 12GB atau 16GB • Penyimpanan Internal: 256GB atau 512GB • Baterai: 5000 mAh • Pengisian Daya: 120W fast charging • Sistem Operasi: OriginOS berbasis Android 14 • Konektivitas: 5G, Wi-Fi 7, Bluetooth 5.3, NFC"))
    productList.add(Product(R.drawable.iqooz9, "IQ00 Z9", 264, CharCategory.SMARTPHONE, 4.5f, "Chipset: Qualcomm Snapdragon 778G • Layar: 6.58 inci, IPS LCD, 120Hz • Resolusi Layar: 2408 x 1080 piksel • Kamera Belakang: 64 MP (wide) + 8 MP (ultrawide) + 2 MP (macro) • Kamera Depan: 16 MP • RAM: 6GB, 8GB, atau 12GB • Penyimpanan Internal: 128GB atau 256GB • Baterai: 5000 mAh • Pengisian Daya: 44W fast charging • Sistem Operasi: OriginOS berbasis Android 13 • Konektivitas: 5G, Wi-Fi 6, Bluetooth 5.2, NFC"))
    productList.add(Product(R.drawable.iqooz7, "IQ00 Z7", 215, CharCategory.SMARTPHONE, 4.5f, "Chipset: MediaTek Dimensity 920 • Layar: 6.64 inci, IPS LCD, 120Hz • Resolusi Layar: 2388 x 1080 piksel • Kamera Belakang: 64 MP (wide) + 2 MP (macro) • Kamera Depan: 16 MP • RAM: 6GB atau 8GB • Penyimpanan Internal: 128GB atau 256GB • Baterai: 5000 mAh • Pengisian Daya: 44W fast charging • Sistem Operasi: OriginOS berbasis Android 13 • Konektivitas: 5G, Wi-Fi 6, Bluetooth 5.2, NFC"))
    return productList
}